version: '3.7'
services:
  mongo:
    image: mongo:4
    container_name: posts_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: postsdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
