name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:7
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              env:
                  MONGO_URI: mongodb://localhost:27017/postsdb
              run: npm test
